config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "public_recipes#index"

  
  resources :recipes, only: [:index, :new, :show, :create] do 
    resources :recipe_foods, only: [:new, :create, :destroy]  
  end
  resources :foods, only: [:index, :new, :show, :create]
  resources :shopping_lists, only: [:index]
  resources :public_recipes, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    cannot :read, Recipe, public: false
    return unless user.present?

    can(:manage, Recipe, user:)
    can(:manage, Food, user:)
    can(:manage, RecipeFood, user:)
    # return unless user.role == 'admin'

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods
  belongs_to :user

  validates :name, presence: true
  validates :price, presence: true, comparison: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, comparison: { greater_than_or_equal_to: 0 }
  validates :measurement_unit, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true, length: { minimum: 5, maximum: 350 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  validates :quantity, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(_scope)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id
    if @food.save
      redirect_to foods_path
    else
      render :new
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.includes([:user, { recipe_foods: :food }]).where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_new = @recipe.recipe_foods.new
    @foods = Food.all
  end

  def create
    @recipe_foods = RecipeFood.new(recipe_foods_params)
    if @recipe_foods.save
      redirect_to recipe_path(params[:recipe_id])
    else
      render :new
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to recipe_path(params[:recipe_id])
  end

  private

  def recipe_foods_params
    params.require(:recipe_food).permit(:quantity, :food_id, :recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # load_and_authorize_resource
  before_action :authenticate_user!, except: [:show]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipes_path, notice: 'recipe added successfully'
    else
      render new, alert: 'sorry an error happened. try again'
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipes = Recipe.includes(:recipe_foods).find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, alert: 'Recipe has been deleted'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :authenticate_user!
  def index
    @all_ingredients = RecipeFood.includes(:recipe, :food)
    @missing = @all_ingredients.select { |ing| ing.quantity > ing.food.quantity }
    @missing_ingredients = @missing.map do |ingredient|
      {
        name: ingredient.food.name,
        quantity: ingredient.quantity - ingredient.food.quantity,
        price: ingredient.food.price * (ingredient.quantity - ingredient.food.quantity)
      }
    end
    @total_price = @missing_ingredients.map { |ing| ing[:price] }.sum
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/index.html.erb
<div class="add_food_button">
    <button>
        <%= link_to 'Add food',new_food_path %>
    </button>
</div>

<table class="food_table">
  <tr>
    <th>Food</th>
    <th>Measurement Unit</th>
    <th>Unit Price</th>
    <th>Actions</th>
  </tr>
    <% @foods.each do |food|%>
        <tr>
            <td><%= food.name%></td>
            <td><%= food.measurement_unit%></td>
            <td><%= food.price%></td>
            <td><%= button_to 'Delete' %></td>
        </tr>
    <% end %>
</table>

app/views/foods/new.html.erb
<div class="food_form_container">
    <%= form_with model: @food, url: foods_path, method: :post do |f|%>
        <div class="food_field">
            <%= f.label :name, "Name" %><br>
            <%= f.text_field :name %>
        </div>
        <br>

        <div class="food_field">
            <%= f.label :measurement_unit, "Measurement Unit" %><br>
            <%= f.text_field :measurement_unit %>
        </div>
        <br>

        <div class="food_field">
            <%= f.label :price %><br>
            <%= f.number_field :price %>
        </div>
        <br>

        <div class="food_field">
            <%= f.label :quantity %><br>
            <%= f.number_field :quantity %>
        </div>
        <br>

        <%= f.submit 'Add food', class:"food_form_submit_button" %><br>
    <% end %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <header>
  <div class="signup">
    <span></span>
      <div class="login-logout">
        <ul class="li-login">
        <% if user_signed_in? %>
          <li><%= button_to "LogOut", destroy_user_session_path, method: :delete, class:"log-btn" %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path, class:"log-btn" %></li>
          <% end %>
        </ul>
      </div>
  </div>
  
  <div class="nav-box">
    <h1>My Recipe App</h1>
      <nav>
        <ul class="nav-list">
          <li><a href="url"><%= link_to "Recipes", recipes_path %></a></a></li>
          <li><a href=""> <%= link_to "Public Recipes", root_path %></a></li>
          <li><a href=""> <%= link_to "Shopping List", shopping_lists_path %></a></li>
          <li><a href=""> <%= link_to "Foods", foods_path %></li>
        </ul>
      </nav>
  </div>

  </header>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<h2> Public Recipe </h2>

<div class="public_recipes_container">

    <% @public_recipes.each do |recipe| %>
        <div class="public_recipe_container">
            <div>
                <h3><%=link_to recipe.name, recipe_path(recipe.id) %></h3>
                <p>By: <%= recipe.user.name %> </p>
            </div>
            <div class="public_recipe_details_container">
                <p>Preparation time: <%= recipe.preparation_time%></p>
                <p>Cooking time: <%= recipe.cooking_time %></p>
            </div>
        </div>
    <% end %>
</div>

app/views/recipe_foods/new.html.erb
<h1>Add new Recipe</h1>

 <%= form_with model: @recipe_new, url: recipe_recipe_foods_path do |f| %>
  <div class="form_control">
      <%= f.label :quantity %>
      <%= f.number_field :quantity %>
    </div>

    <div class="form_control">
    <%= f.select(:food_id, @foods.map{|u| [u.name, u.id]}) %>
    </div>

    <div class="form_control">
    <%= f.hidden_field :recipe_id, value: @recipe_new.recipe_id %>
    </div>
    <%= f.submit "Submit", class:"btn btn-success" %>
<% end%>

app/views/recipes/index.html.erb
<h1> Recipes Index</h1>

<article>
  <div class="recipe-container">
      <h2> <% @recipes.each do |recipe| %> </h2>
      <div class="recipe-box">
        <div class="left-block">
          <h3> <%= link_to recipe.name, recipe_path(recipe.id)  %> </h3>
          <button> Remove </button>
        </div>
        <div class="right-block">
          <p class="recipe-desc"> <%= recipe.description %> </p>
        </div>  
      </div> 
      <% end %>
    
    <button class="add-recipe"><%= link_to "Add  New Recipe", new_recipe_path %></button>


  </div>
</article>

app/views/recipes/new.html.erb
<h1>Add new Recipe</h1>

 <%= form_with model: @recipe, url: recipes_path,  method: :post  do |f| %>
  <div class="form_control">
    <%= f.label :name, "Name" %> <br>
    <%= f.text_field :name %>
  </div>

  <div class="form_control">
    <%= f.label :preparation_time %> <br>
    <%= f.text_field :preparation_time %>
  </div>

  <div class="form_control">
    <%= f.label :cooking_time %> <br>
    <%= f.text_field :cooking_time %>
  </div>

  <div class="form_control">
    <%= f.label :description %> <br>
    <%= f.text_field :description, class:" msg-input" %>
  </div>
  
  <div>
    <%= f.label :public, "Public" %>
    <%= f.check_box :public, value: "true"%>
  </div>

 <%= f.submit 'Add Recipe', class:"add-recipe" %>
<% end%>

app/views/recipes/show.html.erb
<h1>Show Recipes </h1>

  <div class="recipe-details">
      <h2 class="recipe-name"> <%= @recipes.name %> </h2>
    <div class="recipe-status">
      
      <div class="left-block">
        <span>Preparation time : <%= @recipes.preparation_time%> </span>
        <p>Cooking time: <%=  @recipes.cooking_time %> hours</p>
      </div>
      <div class="right-block">
        <span>Public: <%= check_box :public, value: "true"%></span> 
      </div>
  </div>
    <h2> Steps to prepare </h2>

  <%if can? :manage, @recipe %>
  <div class="recipe-actions">
      <%= link_to 'Generate shopping list', shopping_lists_path(@recipes.id), class:"recipe-btn"%>
      <%= link_to 'Add Ingridients', new_recipe_recipe_food_path(@recipes.id), class: "recipe-btn"%>
      </div>
  </div>
  <% else %>
      <div>Please login to add ingredients</div>
  <% end %>
  <hr>

  <table class="food_table">
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>

    <% @recipes.recipe_foods.each do |r_food| %>
    <tr>
      <td> <%= r_food.food.name %> </td>
      <td><%= r_food.quantity%> </td>
      <td><%=r_food.food.price %> </td>
      <td class="mod-btn">
      <%= button_to 'modify', recipe_recipe_food_path(@recipes.id, r_food.id), class:"recipe_table_button" %> 
      <%= button_to ' Remove', recipe_recipe_food_path(@recipes.id, r_food.id), method: :delete, class:"recipe_table_button" %>
      </td>
    </tr>
    <%end%>

  </table>

app/views/shopping_lists/index.html.erb
<div>
    <span>Amount of food items to buy: <%= @missing.count %></span>
    <span>Total value of food needed: $<%= @total_price.floor %></span>
</div>


<table class="food_table">
  <tr>
    <th>Food</th>
    <th>Quantity</th>
    <th>Price</th>
    
  </tr>
    <% @missing_ingredients.each do |food|%>
        <tr>
            <td><%= food[:name]%></td>
            <td><%= food[:quantity]%></td>
            <td><%= food[:price]%></td>
        </tr>
    <% end %>
</table>